appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c33c2b987b5930700c3e954
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: jWZo1f0CPSHAvqrASsa/6Ivcp4rPN8AV2DaJCZX9ODz67zemy52TWbnk8ybZTOkKFBH13uyq5LqpqeYjVFdwF27i8QmdwSwWlNErKmBcydMZy+sbsnEcxGvn5CYJPiVJSnGO1e//8bUUVwRtg91xtKDltuRugIfHJR22GH2u8iyKTRg8A4OarP90JcHzz7PqOWR3Nlq+N9At4gJH9IYvS3+Tg5YBEEy+zaFvzWqgdr4ZMQK9DUfbidCrV7OvAEkANdN88lU3qcdItvl9yCzjZ+pGrOjUNklV+EB79lCEu7smZ4J0Vrrn7EkCzT7vs4AL++x+JDySndXAMnUY9Gcp18QYWEha8m3rpqX6qfkY/xsHftsn1iHZthCv8Izi9H9irW4HAHnDOCU8HXIy+tfPvUABVEGgixhKsGY7TqOj8qqOSu2FK6gXqDjF2SlooFuRkRyyPw07C2OB7sBZ9qibO9Ca99ChsgRGRisB85Tw77BNkGHbpZHqmw6SJhBjiE2ORZGhUNWWahXUIiK9Udyk2DneV1yA3cGUKnrDoe6m2uwT1chqJYTN2wOY+BECXnMGwiJJz/gxwt0ibNdZsUs9Q1bAvw9z9lwHVFe/mIX0QWtEvSTA/PgtRdrmdvjaywya0jMlQJ32O6e3XNuXsPpkmm5EOmkASwvzLSbgJmCrMQA=}
