jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      linux_mpimpich:
        CONFIG: linux_mpimpich
      linux_mpiopenmpi:
        CONFIG: linux_mpiopenmpi
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build